name: Deploy to Azure VM (Self-hosted)

on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install
          
      - name: Restart Node.js app in screen
        run: |
          # Kill old screen session if running
          screen -S spamHamBot -X quit || true
          
          # Start new detached screen session
          screen -dmS spamHamBot bash -c 'node Repos/Node.js/Other/sprusrxeroxx/SpamHammer/testingindex.js'
